
[functions.submit-inquiry]
enabled = true
verify_jwt = true
import_map = "./functions/submit-inquiry/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit-inquiry/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit-inquiry/*.html" ]

[functions.submit-contact]
enabled = true
verify_jwt = true
import_map = "./functions/submit-contact/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/submit-contact/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/submit-contact/*.html" ]

[functions.send-admin-reply]
enabled = true
verify_jwt = true
import_map = "./functions/send-admin-reply/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-admin-reply/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-admin-reply/*.html" ]
